package com.cryptopulse.app;
import java.util.*;
public final class Core {
 public static final String[] SYMBOLS={"BTC","ETH","LINK","LTC","XAU","XAG","SPX500","NAS100","WTI","EUR"};
 public static final String[] NAMES={"Bitcoin","Ethereum","Chainlink","Litecoin","Gold","Silver","S&P 500","Nasdaq 100","WTI crude oil","Euro dollar"};
 public static String name(String s){for(int i=0;i<SYMBOLS.length;i++)if(s.equals(SYMBOLS[i]))return NAMES[i];return s;}
 public static boolean allowedUrl(String url){try{java.net.URI u=new java.net.URI(url);String host=u.getHost();if(!"https".equalsIgnoreCase(u.getScheme())||host==null||u.getUserInfo()!=null)return false;for(String label:host.toLowerCase(Locale.US).split("\\."))if(label.equals("gov"))return false;return true;}catch(Exception e){return false;}}
 public static String unit(String symbol){if(symbol.equals("XAU")||symbol.equals("XAG"))return "dollars per troy ounce";if(symbol.equals("SPX500")||symbol.equals("NAS100"))return "index points";if(symbol.equals("WTI"))return "dollars per barrel";if(symbol.equals("EUR"))return "dollars per euro";return "dollars";}
 public static boolean match(String title,String symbol){String t=" "+title.toLowerCase(Locale.US).replaceAll("[^a-z0-9 ]"," ")+" ";if(symbol.equals("BTC"))t=t.replace("bitcoin cash"," ");String[][] aliases={{"ETH","ether"},{"XAU","gold","bullion"},{"XAG","silver"},{"SPX500","s p 500","s p500","sp500"},{"NAS100","nasdaq","nasdaq 100"},{"WTI","oil","crude","petroleum","opec"},{"EUR","eur usd","euro","forex"}};if(t.contains(" "+symbol.toLowerCase(Locale.US)+" ")||t.contains(" "+name(symbol).toLowerCase(Locale.US).replaceAll("[^a-z0-9 ]"," ")+" "))return true;for(String[] a:aliases)if(a[0].equals(symbol))for(int i=1;i<a.length;i++)if(t.contains(" "+a[i]+" "))return true;return false;}
 public static boolean cryptoHeadline(String title){String t=" "+title.toLowerCase(Locale.US).replaceAll("[^a-z0-9 ]"," ")+" ";for(String word:new String[]{"bitcoin","ethereum","ether","chainlink","litecoin","crypto","cryptocurrency","cryptocurrencies","token","tokens","blockchain","altcoin","altcoins","meme coin","web3","defi","airdrop","staking","solana","dogecoin","cardano","xrp","shiba","pepe","presale"})if(t.contains(" "+word+" "))return true;return false;}
 public static String priceText(String symbol,double price){return String.format(Locale.US,symbol.equals("EUR")?"%.5f":"%.2f",price)+" "+unit(symbol);}
 public static double percent(double now,double base){if(!Double.isFinite(now)||!Double.isFinite(base)||now<=0||base<=0)throw new IllegalArgumentException("Invalid price");return (now/base-1)*100;}
 public static boolean quiet(int hour,int from,int to){return from==to|| (from<to?hour>=from&&hour<to:hour>=from||hour<to);}
 public static Set<String> words(String t){Set<String>s=new HashSet<>();for(String x:t.toLowerCase(Locale.US).replaceAll("[^a-z0-9 ]"," ").split("\\s+"))if(x.length()>2&&!Arrays.asList("the","and","for","with","from","that","this","says","after","amid","into","its","are","has","new","how","why").contains(x))s.add(x);return s;}
 public static Set<String> anchors(String title){Set<String>s=new HashSet<>();for(String symbol:SYMBOLS)if(match(title,symbol))s.add(symbol);return s;}
 public static boolean duplicate(String a,String b,double threshold){Set<String>ca=anchors(a),cb=anchors(b);if(!ca.isEmpty()&&!cb.isEmpty()&&!ca.equals(cb))return false;Set<String>x=words(a),y=words(b);if(x.isEmpty()||y.isEmpty())return a.equalsIgnoreCase(b);Set<String>u=new HashSet<>(x);u.addAll(y);x.retainAll(y);return (double)x.size()/u.size()>=threshold;}
 public static boolean relevant(String title,Set<String>selected,boolean macro){String t=" "+title.toLowerCase(Locale.US).replaceAll("[^a-z0-9 ]"," ")+" ";boolean selectedCrypto=false;for(String coin:new String[]{"BTC","ETH","LINK","LTC"})if(selected.contains(coin)&&match(title,coin))selectedCrypto=true;if(cryptoHeadline(title)&&!selectedCrypto)return false;for(String s:selected)if(match(title,s))return true; if(!macro)return false;for(String k:new String[]{"federal reserve","interest rate","inflation","treasury","fomc","central bank","monetary policy","jobs report","consumer price","cpi","crypto regulation","bitcoin etf","crypto market","cryptocurrency market","digital asset regulation","stock market","stocks","shares","equities","earnings","financial market","business","economy","economic","bank","bonds","dollar","tariff","trade war","wall street","nasdaq","s p 500","dow jones","bond yield","unemployment","nonfarm payroll","bank failure","recession"})if(t.contains(k))return true;return false;}
 public static class Story {public String title,url,source,summary;public int rank;public long time;public Story(String t,String u,String s,String d,int r,long p){title=t;url=u;source=s;summary=d;rank=r;time=p;}}
 public static List<Story> rankAndGroup(List<Story> in,double threshold){List<Story>out=new ArrayList<>();in.sort((a,b)->a.rank!=b.rank?Integer.compare(a.rank,b.rank):Long.compare(b.time,a.time));for(Story s:in){boolean dup=false;for(Story o:out)if(duplicate(s.title,o.title,threshold)){dup=true;break;}if(!dup)out.add(s);}out.sort((a,b)->Long.compare(b.time,a.time));return out;}
 public static String alertMessage(String symbol,double change){return String.format(Locale.US,"%s %s %.2f%%",symbol,change>=0?"up":"down",Math.abs(change));}
 public static boolean alertDue(double price,double baseline,double threshold,long now,long previous,long cooldownSeconds){return Math.abs(percent(price,baseline))+1e-9>=threshold&&now-previous>=cooldownSeconds*1000L;}
 public static String change(double d){return String.format(Locale.US,"%s %.2f percent",d>=0?"up":"down",Math.abs(d));}
}
