package com.cryptopulse.app;
import java.net.*;import java.io.*;import java.util.*;import java.text.*;import org.json.*;
final class Fetcher {
 static String get(String url)throws Exception{URL u=new URL(url);for(int redirect=0;redirect<5;redirect++){if(!Core.allowedUrl(u.toString()))throw new IOException("HTTPS required; .gov, CNBC and MarketWatch hosts are blocked");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(10000);c.setReadTimeout(12000);c.setInstanceFollowRedirects(false);c.setRequestProperty("User-Agent","CryptoPulseAudio/1.1 (+Android personal RSS reader)");c.setRequestProperty("Accept","application/json, application/rss+xml, application/atom+xml, application/xml, text/xml, */*");try{int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");if(loc==null)throw new IOException("Missing redirect");u=new URL(u,loc);continue;}if(code!=200)throw new IOException("HTTP "+code);try(InputStream in=c.getInputStream();ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[]buf=new byte[8192];int n;while((n=in.read(buf))!=-1){b.write(buf,0,n);if(b.size()>2000000)throw new IOException("Response exceeds 2 MB");}return b.toString("UTF-8");}}finally{c.disconnect();}}throw new IOException("Too many redirects");}
 static final java.util.concurrent.ConcurrentHashMap<String,String> etags=new java.util.concurrent.ConcurrentHashMap<>(),modified=new java.util.concurrent.ConcurrentHashMap<>();
 static class Response {String body;boolean notModified;Response(String b,boolean unchanged){body=b;notModified=unchanged;}}
 static Response cached(String url)throws Exception{URL u=new URL(url);for(int redirects=0;redirects<5;redirects++){if(!Core.allowedUrl(u.toString()))throw new IOException("HTTPS required; .gov, CNBC and MarketWatch hosts are blocked");HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(6000);c.setReadTimeout(8000);c.setInstanceFollowRedirects(false);c.setRequestProperty("User-Agent","CryptoPulseAudio/1.1 (+Android personal RSS reader)");c.setRequestProperty("Accept","application/rss+xml, application/atom+xml, application/xml, text/xml, */*");if(etags.containsKey(url))c.setRequestProperty("If-None-Match",etags.get(url));if(modified.containsKey(url))c.setRequestProperty("If-Modified-Since",modified.get(url));try{int code=c.getResponseCode();if(code==304)return new Response("",true);if(code>=300&&code<400){String loc=c.getHeaderField("Location");if(loc==null)throw new IOException("Missing redirect");u=new URL(u,loc);continue;}if(code!=200)throw new IOException("HTTP "+code);String etag=c.getHeaderField("ETag"),last=c.getHeaderField("Last-Modified");String body;try(InputStream in=c.getInputStream();ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[]buf=new byte[8192];int n;while((n=in.read(buf))!=-1){b.write(buf,0,n);if(b.size()>2000000)throw new IOException("Feed exceeds 2 MB");}body=b.toString("UTF-8");}if(etag!=null)etags.put(url,etag);else etags.remove(url);if(last!=null)modified.put(url,last);else modified.remove(url);return new Response(body,false);}finally{c.disconnect();}}throw new IOException("Too many redirects");}
 static List<Core.Story> feed(String xml,String source,int rank)throws Exception{return FeedReader.parse(xml,source,rank);}
}
