package com.cryptopulse.app;
import org.java_websocket.client.WebSocketClient;import org.java_websocket.handshake.ServerHandshake;import org.json.*;import java.net.URI;import java.util.*;import java.util.concurrent.*;
/** Persistent public price connection; no wallet, keys, orders or trading operations. */
public final class GainsFeed {
 public interface Listener {void ticks(List<PriceParser.Tick> t);void status(String s);void registrySaved(String raw);}
 final Listener listener;final java.util.function.Consumer<WebSocketClient> configure;final ScheduledExecutorService jobs=Executors.newScheduledThreadPool(2);volatile Map<Integer,String>pairs=Collections.emptyMap();volatile WebSocketClient socket;volatile boolean stopped=false,bootstrapping=false;volatile long lastFrame=0,lastConnect=0,checkpoint=0,nextConnect=0,lastSnapshot=0,registryAt=0;int retry=0;String lastStatus="";
 public GainsFeed(Listener l,String cached){this(l,cached,client->{});}
 public GainsFeed(Listener l,String cached,java.util.function.Consumer<WebSocketClient> config){listener=l;configure=config;try{pairs=PriceParser.registry(cached);}catch(Exception ignored){}}
 private synchronized void state(String s){if(!s.equals(lastStatus)){lastStatus=s;listener.status(s);}}
 public void start(){jobs.execute(()->bootstrap());jobs.scheduleWithFixedDelay(()->{if(stopped)return;long now=System.currentTimeMillis();WebSocketClient s=socket;if(s!=null&&s.isOpen()&&now-lastFrame>20000){state("Gains stream silent • reconnecting");s.close();}if((s==null||s.isClosed())&&now>=nextConnect)connect();if((pairs.isEmpty()||s==null||!s.isOpen())&&now-lastSnapshot>60000&&!bootstrapping)bootstrap();},0,2,TimeUnit.SECONDS);}
 private void bootstrap(){if(stopped||bootstrapping)return;bootstrapping=true;try{if(pairs.isEmpty()||System.currentTimeMillis()-registryAt>6*3600000L){try{String raw=Fetcher.get("https://backend-polygon.gains.trade/trading-variables/pairs");Map<Integer,String>found=PriceParser.registry(raw);if(found.isEmpty())throw new Exception("Market registry unavailable");pairs=found;registryAt=System.currentTimeMillis();listener.registrySaved(raw);}catch(Exception ex){if(pairs.isEmpty())throw ex;state("Using cached Gains market registry");}}if(!stopped){lastSnapshot=System.currentTimeMillis();List<PriceParser.Tick>ticks=PriceParser.snapshot(Fetcher.get("https://backend-pricing.eu.gains.trade/charts"),pairs,System.currentTimeMillis());if(!stopped)listener.ticks(ticks);}}catch(Exception e){state("Gains bootstrap unavailable • "+e.getMessage());lastSnapshot=System.currentTimeMillis();}finally{bootstrapping=false;}}
 private synchronized void connect(){if(stopped)return;lastConnect=System.currentTimeMillis();checkpoint=0;state("Connecting to Gains live prices");try{WebSocketClient s=new WebSocketClient(new URI("wss://backend-pricing.eu.gains.trade/v4"),Collections.singletonMap("User-Agent","CryptoPulseAudio/1.1")){public void onOpen(ServerHandshake sh){if(stopped||socket!=this)return;lastFrame=System.currentTimeMillis();retry=0;state("Gains live connected");}public void onMessage(String raw){if(stopped||socket!=this)return;long now=System.currentTimeMillis();lastFrame=now;try{if(raw.trim().startsWith("[")){JSONArray a=new JSONArray(raw);if(a.length()==1){long t=PriceParser.stamp(a.optLong(0,0));if(t>0&&t<=now+5000&&now-t<=30000)checkpoint=t;return;}}List<PriceParser.Tick>ticks=PriceParser.frame(raw,pairs,now,checkpoint);if(!ticks.isEmpty())listener.ticks(ticks);}catch(Exception e){state("Invalid Gains frame • waiting for recovery");}}public void onClose(int code,String reason,boolean remote){if(stopped||socket!=this)return;nextConnect=System.currentTimeMillis()+Math.min(30000,1000L<<Math.min(retry++,5));state("Gains disconnected ("+code+") • "+reason+" • automatic retry");}public void onError(Exception e){if(stopped||socket!=this)return;state("Gains connection error • "+e.getClass().getSimpleName()+": "+e.getMessage()+" • retrying");}};socket=s;configure.accept(s);s.setConnectionLostTimeout(15);s.connect();}catch(Exception e){nextConnect=System.currentTimeMillis()+5000;state("Unable to connect to Gains • retrying");}}
 public void refresh(){if(!stopped)jobs.execute(()->bootstrap());}
 public void close(){stopped=true;WebSocketClient s=socket;if(s!=null)s.close();jobs.shutdownNow();}
}
