package com.cryptopulse.app;
import java.util.*;import org.json.*;
/** Public Gains identifiers are resolved by exact base/quote, never by ticker substring. */
public final class PriceParser {
 public static class Tick {public final String symbol,type;public final int pair;public final double price;public final long time;public Tick(String s,int id,double p,long t,String ty){symbol=s;pair=id;price=p;time=t;type=ty;}}
 public static Map<Integer,String> registry(String raw)throws Exception{JSONObject j=new JSONObject(raw);JSONArray a=j.getJSONArray("pairs");Map<Integer,String>out=new HashMap<>();Set<String>names=new HashSet<>(Arrays.asList(Core.SYMBOLS));for(int k=0;k<a.length();k++){JSONObject p=a.optJSONObject(k);if(p==null)continue;String base=p.optString("from");if(names.contains(base)&&p.optString("to").equals("USD"))out.put(k,base);}return out;}
 public static long stamp(long t){return t>=1000000000L&&t<1000000000000L?t*1000:t;}
 static boolean valid(double p){return Double.isFinite(p)&&p>0;}
 public static List<Tick> frame(String raw,Map<Integer,String>pairs,long received,long checkpoint)throws Exception{if(raw==null||raw.length()>1000000)return Collections.emptyList();List<Tick>out=new ArrayList<>();String trimmed=raw.trim();if(trimmed.startsWith("{")){JSONObject j=new JSONObject(raw);long t=stamp(j.optLong("t",received));if(t<=0||t>received+5000||received-t>30000)return out;Set<Integer>done=new HashSet<>();apply(j.optJSONArray("i"),pairs,t,"index",out,done);apply(j.optJSONArray("m"),pairs,t,"mark",out,done);}else{JSONArray a=new JSONArray(raw);if(a.length()==1)return out;long t=checkpoint>0?checkpoint:received;if(t>received+5000||received-t>30000)return out;apply(a,pairs,t,"live",out,new HashSet<>());}return out;}
 static void apply(JSONArray a,Map<Integer,String>pairs,long time,String type,List<Tick>out,Set<Integer>done){if(a==null||a.length()%2!=0)return;for(int k=0;k<a.length();k+=2){Object id=a.opt(k),value=a.opt(k+1);if(!(id instanceof Number)||!(value instanceof Number))continue;double n=((Number)id).doubleValue(),p=((Number)value).doubleValue();if(n!=Math.rint(n)||n<0||n>10000||!valid(p))continue;int pair=(int)n;String s=pairs.get(pair);if(s!=null&&done.add(pair))out.add(new Tick(s,pair,p,time,type));}}
 public static List<Tick> snapshot(String raw,Map<Integer,String>pairs,long now)throws Exception{JSONObject j=new JSONObject(raw);long time=stamp(j.optLong("time",0));if(time<=0||time>now+5000||now-time>120000)return Collections.emptyList();JSONArray indices=j.optJSONArray("indexPrices"),marks=j.optJSONArray("closes");List<Tick>out=new ArrayList<>();for(Map.Entry<Integer,String>e:pairs.entrySet()){int id=e.getKey();double p=indices==null?Double.NaN:indices.optDouble(id,Double.NaN);String type="snapshot index";if(!valid(p)){p=marks==null?Double.NaN:marks.optDouble(id,Double.NaN);type="snapshot mark";}if(valid(p))out.add(new Tick(e.getValue(),id,p,time,type));}return out;}
}
