package com.cryptopulse.app;
import android.content.*;import org.json.*;import java.util.*;
final class Store {
 static final String[][] SOURCES={{"CoinDesk","https://www.coindesk.com/arc/outboundfeeds/rss/","1"},{"Bloomberg Markets","https://feeds.bloomberg.com/markets/news.rss","3"},{"Financial Times","https://www.ft.com/rss/home","5"},{"BBC Business","https://feeds.bbci.co.uk/news/business/rss.xml","6"},{"Guardian Business","https://www.theguardian.com/business/rss","7"},{"Investing Commodities","https://www.investing.com/rss/news_11.rss","8"},{"FXStreet","https://www.fxstreet.com/rss/news","9"},{"Decrypt","https://decrypt.co/feed","10"},{"Cointelegraph","https://cointelegraph.com/rss","11"}};
 static boolean businessSource(String name){return Arrays.asList("Bloomberg Markets","Financial Times","BBC Business","Guardian Business","Investing Commodities","FXStreet").contains(name);}
 static List<String[]> sources(Context c){List<String[]> out=new ArrayList<>();Collections.addAll(out,SOURCES);JSONArray a=array(c,"customSources");for(int i=0;i<a.length();i++){JSONObject j=a.optJSONObject(i);if(j!=null&&Core.allowedUrl(j.optString("url"))&&!Core.removedSourceName(j.optString("name")))out.add(new String[]{j.optString("name"),j.optString("url"),""+j.optInt("rank",11)});}return out;}
 static android.content.SharedPreferences p(Context c){return c.getSharedPreferences("pulse",0);}
 static int number(Context c,String k,int d){return p(c).getInt(k,d);} static boolean yes(Context c,String k,boolean d){return p(c).getBoolean(k,d);}static String text(Context c,String k,String d){return p(c).getString(k,d);}
 static Set<String> coins(Context c){Set<String> s=new HashSet<>(p(c).getStringSet("coins",new HashSet<>(Arrays.asList("BTC","ETH","LINK","LTC","XAU","XAG","SPX500","NAS100","WTI"))));s.retainAll(Arrays.asList(Core.SYMBOLS));return s;}
 static void migrateLegacy(Context c){if(number(c,"schema",0)>=2)return;android.content.SharedPreferences.Editor e=p(c).edit();e.putStringSet("coins",new HashSet<>(Arrays.asList("BTC","ETH","LINK","LTC","XAU","XAG","SPX500","NAS100","WTI"))).putInt("newsSeconds",60).putInt("threshold",25).putInt("cooldownSeconds",30).putInt("maxStories",10).putInt("schema",2).remove("source_Federal Reserve").remove("rank_Federal Reserve").remove("health_Federal Reserve").remove("checked_Federal Reserve");for(String symbol:Core.SYMBOLS)e.remove("base_"+symbol).remove("baseTime_"+symbol).remove("alertAt_"+symbol).remove("sessionBase_"+symbol).remove("sessionAt_"+symbol);e.apply();save(c,"quotes",new JSONArray());for(String key:new String[]{"stories","seen","customSources"}){JSONArray old=array(c,key),out=new JSONArray();for(int i=0;i<old.length();i++){JSONObject j=old.optJSONObject(i);if(j!=null&&Core.allowedUrl(j.optString("url"))&&!j.optString("source").equals("Federal Reserve"))out.put(j);}save(c,key,out);}save(c,"pending",new JSONArray());save(c,"log",new JSONArray());p(c).edit().remove("lastSpoken").remove("spokenAt").apply();}
 static void migrate(Context c){migrateLegacy(c);if(number(c,"schema",0)>=3)return;
  android.content.SharedPreferences.Editor edit=p(c).edit();for(String key:p(c).getAll().keySet()){for(String prefix:new String[]{"source_","rank_","health_","checked_"})if(key.startsWith(prefix)&&Core.removedSourceName(key.substring(prefix.length())))edit.remove(key);for(String prefix:new String[]{"etag:","modified:"})if(key.startsWith(prefix)&&!Core.allowedUrl(key.substring(prefix.length())))edit.remove(key);}edit.putInt("schema",3).putBoolean("clearOldNotifications",true).apply();
  for(String key:new String[]{"stories","seen","customSources"}){JSONArray old=array(c,key),out=new JSONArray();for(int i=0;i<old.length();i++){JSONObject item=old.optJSONObject(i);if(item!=null&&Core.allowedUrl(item.optString("url"))&&!Core.removedSourceName(item.optString("source"))&&!Core.removedSourceName(item.optString("name")))out.put(item);}save(c,key,out);}
  JSONArray old=array(c,"pending"),out=new JSONArray();for(int i=0;i<old.length();i++){JSONObject item=old.optJSONObject(i);if(item!=null&&!item.optString("type").startsWith("price_")&&!item.optString("type").equals("digest")&&!Core.removedNewsSpeech(item.optString("text")))out.put(item);}save(c,"pending",out);
  old=array(c,"log");out=new JSONArray();for(int i=0;i<old.length();i++){String line=old.optString(i);String text=line.substring(line.indexOf('|')+1);if(!Core.removedNewsSpeech(text)&&!text.matches("(?s).*(?:up|down) 0\\.00%.*"))out.put(line);}save(c,"log",out);p(c).edit().remove("lastSpoken").remove("spokenAt").putLong("activityAt",System.currentTimeMillis()).apply();
 }
 static volatile String currentQuotes=null;static long quotesSaved=0;
 static synchronized void publishQuotes(Context c,JSONArray quotes,long now){currentQuotes=quotes.toString();if(now-quotesSaved>30000){quotesSaved=now;save(c,"quotes",quotes);p(c).edit().putLong("priceChecked",now).apply();}}
 static synchronized JSONArray array(Context c,String k){try{return new JSONArray(k.equals("quotes")&&currentQuotes!=null?currentQuotes:text(c,k,"[]"));}catch(Exception e){return new JSONArray();}}
 static synchronized void save(Context c,String k,JSONArray a){p(c).edit().putString(k,a.toString()).apply();}
 static synchronized void log(Context c,String t){JSONArray a=array(c,"log");JSONArray out=new JSONArray();out.put(System.currentTimeMillis()+"|"+t);for(int i=0;i<Math.min(79,a.length());i++)out.put(a.optString(i));save(c,"log",out);p(c).edit().putLong("activityAt",System.currentTimeMillis()).apply();}
 static synchronized void addStory(Context c,Core.Story s){JSONArray a=array(c,"stories"),out=new JSONArray();try{JSONObject j=new JSONObject();j.put("title",s.title).put("url",s.url).put("source",s.source).put("time",s.time).put("rank",s.rank).put("summary",s.summary);out.put(j);for(int i=0;i<Math.min(99,a.length());i++)out.put(a.get(i));save(c,"stories",out);}catch(Exception e){}}
 static synchronized boolean seen(Context c,Core.Story s,double sim){JSONArray a=array(c,"seen");long cutoff=System.currentTimeMillis()-7*86400000L;for(int i=0;i<a.length();i++){JSONObject j=a.optJSONObject(i);if(j!=null&&j.optLong("time")>cutoff&&(s.url.equals(j.optString("url"))||Core.duplicate(s.title,j.optString("title"),sim)))return true;}return false;}
 static synchronized void mark(Context c,Core.Story s){JSONArray a=array(c,"seen"),out=new JSONArray();try{out.put(new JSONObject().put("title",s.title).put("url",s.url).put("time",System.currentTimeMillis()));for(int i=0;i<a.length()&&out.length()<1000;i++){JSONObject j=a.optJSONObject(i);if(j!=null&&j.optLong("time")>System.currentTimeMillis()-7*86400000L)out.put(j);}save(c,"seen",out);}catch(Exception e){}}
}
