import com.cryptopulse.app.*;import java.util.*;import java.nio.file.*;
public class CoreTest {
 static int tests;static void check(boolean yes,String name){tests++;if(!yes)throw new AssertionError(name);}
 public static void main(String[]args)throws Exception{
  check(Math.abs(Core.percent(110,100)-10)<1e-8,"positive percent");check(Math.abs(Core.percent(90,100)+10)<1e-8,"negative percent");
  for(double invalid:new double[]{0,-1,Double.NaN,Double.POSITIVE_INFINITY}){boolean rejected=false;try{Core.percent(invalid,100);}catch(IllegalArgumentException e){rejected=true;}check(rejected,"invalid price rejected");}
  check(Core.quiet(23,22,7)&&Core.quiet(3,22,7)&&!Core.quiet(12,22,7),"overnight quiet");check(Core.quiet(10,9,17)&&!Core.quiet(20,9,17),"daytime quiet");check(Core.quiet(7,7,7),"all day quiet");
  Set<String>coins=new HashSet<>(Arrays.asList("BTC","ETH"));check(Core.relevant("Bitcoin market update",coins,false),"Bitcoin");check(Core.relevant("Ether trading volume rises",coins,false),"Ether alias");check(!Core.relevant("New meme token moonshot",coins,true),"altcoin rejected");check(!Core.relevant("Solana volume rises",coins,false),"unselected crypto rejected");check(Core.relevant("Federal Reserve announces interest rate decision",coins,true),"macro accepted");check(!Core.relevant("Federal Reserve announces interest rate decision",coins,false),"macro disabled");
  check(Core.duplicate("Bitcoin ETF inflows hit record after rally","Bitcoin ETF inflows hit record amid rally",.6),"near duplicate");check(!Core.duplicate("Bitcoin ETF inflows hit record","Bitcoin miners face energy cost crisis",.6),"different events");check(!Core.duplicate("Bitcoin rises 5 percent","Bitcoin falls 5 percent",.6),"direction change distinct");
  Core.Story low=new Core.Story("Bitcoin ETF inflows hit record amid rally","https://a","Low","",8,200),high=new Core.Story("Bitcoin ETF inflows hit record after rally","https://b","High","",1,100);List<Core.Story>group=Core.rankAndGroup(new ArrayList<>(Arrays.asList(low,high)),.6);check(group.size()==1&&group.get(0).source.equals("High"),"highest rank wins duplicate even if older");
  String rss="<rss><channel><item><title>Bitcoin &amp; Ethereum update</title><link>https://example.com/a</link><description>&lt;p&gt;A short summary&lt;/p&gt;</description><pubDate>Tue, 06 Oct 2026 15:00:00 +0000</pubDate></item></channel></rss>";List<Core.Story>parsed=FeedReader.parse(rss,"Test",3);check(parsed.size()==1&&parsed.get(0).title.equals("Bitcoin & Ethereum update"),"RSS title entities");check(parsed.get(0).summary.equals("A short summary"),"HTML stripped");
  String atom="<feed xmlns='http://www.w3.org/2005/Atom'><entry><title>Ethereum news</title><link href='https://example.com/e' rel='alternate'/><published>2026-10-06T15:00:00Z</published><summary>Summary</summary></entry></feed>";check(FeedReader.parse(atom,"Atom",4).get(0).url.equals("https://example.com/e"),"Atom link");check(FeedReader.date("Mon, 5 Oct 2026 20:30:00 GMT")>0,"Fed RFC date");check(FeedReader.date("2026-10-06T15:00:00.000Z")>0,"fractional date");
  check(!Core.duplicate("Bitcoin ETF inflows hit record after rally","Ethereum ETF inflows hit record after rally",.6),"different coins must stay distinct");check(FeedReader.parse("\uFEFF"+rss,"BOM",1).size()==1,"UTF-8 BOM accepted");
  boolean rejected=false;try{FeedReader.parse("<!DOCTYPE rss [<!ENTITY x SYSTEM 'file:///etc/passwd'>]>"+rss,"X",1);}catch(Exception e){rejected=true;}check(rejected,"XXE/DTD rejected");
  rejected=false;try{FeedReader.parse(rss.replace("Tue, 06 Oct 2026 15:00:00 +0000","invalid"),"X",1);}catch(Exception e){rejected=true;}check(rejected,"undated story not new");
  for(String path:args){String xml=new String(Files.readAllBytes(Paths.get(path)),"UTF-8");List<Core.Story>a=FeedReader.parse(xml,path,1);check(!a.isEmpty(),"live feed "+path);System.out.println("Feed parsed: "+path+" ("+a.size()+" dated stories)");}
  System.out.println("PASS: "+tests+" checks");
 }
}
