import com.cryptopulse.app.*;import java.util.*;import java.util.concurrent.*;import java.nio.file.*;import java.util.regex.*;
/** Optional integration check: production HTTP parser and production Gains WebSocket client. */
public class LiveTest {
 public static void main(String[]args)throws Exception{
  RuntimeProxy.configure();CountDownLatch enough=new CountDownLatch(1);Set<String>live=ConcurrentHashMap.newKeySet();Set<String>snapshot=ConcurrentHashMap.newKeySet();GainsFeed feed=new GainsFeed(new GainsFeed.Listener(){public void status(String s){System.out.println("Transport: "+s);}public void registrySaved(String s){}public void ticks(List<PriceParser.Tick>ticks){for(PriceParser.Tick t:ticks){if(t.type.startsWith("snapshot"))snapshot.add(t.symbol);else live.add(t.symbol);}if(live.containsAll(Arrays.asList("BTC","ETH","LINK","LTC"))&&snapshot.containsAll(Arrays.asList(Core.SYMBOLS)))enough.countDown();}},"",RuntimeProxy::webSocket);feed.start();try{boolean ok=enough.await(35,TimeUnit.SECONDS);System.out.println("Live markets received: "+live);System.out.println("Snapshot markets: "+snapshot);if(!ok)throw new AssertionError("Missing expected 24-hour live crypto updates or ten-market bootstrap snapshot");}finally{feed.close();}
  if(args.length>0&&args[0].equals("--stream")){System.out.println("PASS: production live price stream");return;}
  String store=new String(Files.readAllBytes(Paths.get("app/src/main/java/com/cryptopulse/app/Store.java")),"UTF-8");Matcher m=Pattern.compile("\\{\\\"([^\\\"]+)\\\",\\\"(https://[^\\\"]+)\\\",\\\"[0-9]+\\\"\\}").matcher(store);int sources=0;while(m.find()){String name=m.group(1),url=m.group(2);if(!Core.allowedUrl(url))throw new AssertionError("Forbidden source");String xml=ProductionHttp.get(url);List<Core.Story>stories=FeedReader.parse(xml,name,1);System.out.println("Feed OK: "+name+" ("+stories.size()+" dated items)");sources++;}if(sources!=9)throw new AssertionError("Expected expanded source catalog");System.out.println("PASS: live stream and "+sources+" production feeds");
 }
}
