import com.cryptopulse.app.*;import java.util.*;import org.json.*;
public class PriceTest {
 static int count;static void check(boolean good,String name){count++;if(!good)throw new AssertionError(name);}
 public static void main(String[]args)throws Exception{
  Map<Integer,String>pairs=PriceParser.registry("{\"pairs\":[{\"from\":\"BTC\",\"to\":\"USD\"},{\"from\":\"SPX\",\"to\":\"USD\"},{\"from\":\"SPX500\",\"to\":\"USD\"},{\"from\":\"XAU\",\"to\":\"USD\"},{\"from\":\"SOL\",\"to\":\"USD\"}]}");
  check(pairs.size()==3&&!pairs.containsKey(1)&&!pairs.containsKey(4),"do not map SPX token or removed crypto");check(pairs.get(2).equals("SPX500"),"exact index match");long now=1791320100000L;
  List<PriceParser.Tick>ticks=PriceParser.frame("{\"t\":"+now+",\"i\":[0,100,3,4000],\"m\":[0,101,2,6000]}",pairs,now,0);check(ticks.size()==3,"v4 prices filter and fallback");check(ticks.get(0).price==100&&ticks.get(0).type.equals("index"),"index preferred over mark");
  check(PriceParser.frame("[0,100,1,2,3,4000]",pairs,now,now).size()==2,"legacy array compatibility");check(PriceParser.frame("["+now+"]",pairs,now,0).isEmpty(),"checkpoint not a price");check(PriceParser.frame("[0,100,3]",pairs,now,0).isEmpty(),"odd flat frame rejected");check(PriceParser.frame("[0,-1,3,0]",pairs,now,0).isEmpty(),"bad prices rejected");check(PriceParser.frame("[0.5,100,\"0\",100]",pairs,now,0).isEmpty(),"malformed IDs rejected");check(PriceParser.frame("{\"t\":"+(now-31000)+",\"i\":[0,100]}",pairs,now,0).isEmpty(),"old frame rejected");check(PriceParser.frame("{\"t\":"+(now+6000)+",\"i\":[0,100]}",pairs,now,0).isEmpty(),"future frame rejected");
  ticks=PriceParser.snapshot("{\"time\":"+now+",\"indexPrices\":[100,null,6000,4000],\"closes\":[110,2,6100,4100]}",pairs,now);check(ticks.size()==3&&ticks.stream().anyMatch(t->t.symbol.equals("XAU")&&t.price==4000),"snapshot index preference");check(PriceParser.snapshot("{\"time\":"+(now-120001)+",\"closes\":[100]}",pairs,now).isEmpty(),"old snapshot rejected");
  check(Core.allowedUrl("https://news.example.com/rss?source=.gov"),"query is not a government host");check(!Core.allowedUrl("https://www.federalreserve.gov/feed"),"government feed blocked");check(!Core.allowedUrl("https://news.GOV.uk/feed"),"international government subdomain blocked");check(!Core.allowedUrl("http://news.example.com/feed"),"HTTPS enforced");check(!Core.allowedUrl("https://user:pass@news.example.com/feed"),"credentials rejected");check(Core.allowedUrl("https://governance.example.com/feed"),"regular host allowed");
  check(Core.match("Gold prices rise on bullion demand","XAU"),"gold alias");check(Core.match("S&P 500 index climbs","SPX500"),"index alias");check(Core.match("Oil prices slip","WTI"),"oil alias");check(!Core.match("Bitcoin Cash rally","BTC"),"Bitcoin Cash not Bitcoin");Set<String>selected=new HashSet<>(Arrays.asList("BTC","ETH","LINK","LTC","XAU","XAG","SPX500","NAS100","WTI"));check(!Core.relevant("Solana shares jump in crypto market",selected,true),"removed crypto excluded even in macro language");check(Core.relevant("Gold climbs as stocks fall",selected,true),"noncrypto financial news retained");check(!Core.cryptoHeadline("Whether stocks rise depends on earnings"),"ether substring false positive prevented");
  for(String symbol:Core.SYMBOLS)check(Core.alertMessage(symbol,.13).equals(symbol+" up 0.13%"),"clean ticker first "+symbol);
  check(Core.alertMessage("ETH",-.13).equals("ETH down 0.13%"),"negative clean message");check(Core.alertMessage("BTC",0).isEmpty(),"zero is silent");
  for(double d:new double[]{0,-0.0,.000001,-.000001,.0049,-.0049,Double.NaN,Double.POSITIVE_INFINITY,Double.NEGATIVE_INFINITY})check(Core.alertMessage("BTC",d).isEmpty(),"rounded zero/invalid never spoken: "+d);
  check(Core.alertMessage("BTC",.005).equals("BTC up 0.01%"),"positive rounding boundary");check(Core.alertMessage("BTC",-.005).equals("BTC down 0.01%"),"negative rounding boundary");check(Core.alertMessage("ETH",-.125).equals("ETH down 0.13%"),"two-decimal HALF_UP rounding");
  check(Core.cleanPriceSpeech("BTC up 0.00%. ETH down 0.00%.").isEmpty(),"zero-only digest silent");check(Core.cleanPriceSpeech("BTC up 0.00%. ETH down 0.13%. XAU up 0.00%.").equals("ETH down 0.13%"),"mixed digest retains real move only");check(Core.cleanPriceSpeech("BTC up 0.13%").equals("BTC up 0.13%"),"clean alert retained");check(Core.cleanPriceSpeech("Bitcoin up 0.13%").isEmpty(),"no extra market-name speech");check(Core.cleanPriceSpeech("SOL up 1.00%").isEmpty(),"unsupported ticker excluded from speech");
  for(String url:new String[]{"https://cnbc.com/feed","https://search.cnbc.com/rss","https://feeds.marketwatch.com/topstories/","https://WWW.MARKETWATCH.COM./a"})check(!Core.allowedUrl(url),"removed publisher URL blocked: "+url);
  check(Core.allowedUrl("https://news.example.com/?source=cnbc.com"),"publisher string in query does not block independent site");check(Core.allowedUrl("https://cnbc.com.example.org/feed"),"host boundary respected");check(Core.removedSourceName("CNBC Markets")&&Core.removedSourceName("Custom: MarketWatch"),"legacy/custom source labels removed");check(Core.removedNewsSpeech("CNBC Markets reports. Old story")&&Core.removedNewsSpeech("MarketWatch reports. Old story"),"old excluded speech blocked");check(!Core.removedNewsSpeech("Bloomberg Markets reports. CNBC shares fall"),"independent reporting retained");
  check(Core.alertDue(101,100,.25,100000,60000,30),"immediate threshold crossing");check(!Core.alertDue(101,100,.25,100000,95000,30),"cooldown suppresses repeat");check(Core.alertDue(101,100,.25,100000,100000,0),"zero cooldown supported");check(!Core.alertDue(100.1,100,.25,100000,0,0),"small move below threshold");check(Core.alertDue(100.25,100,.25,100000,0,0),"exact threshold included");
  check(FeedReader.date("2026-10-06 20:31:28")>0,"Investing date supported");boolean blocked=false;try{FeedReader.parse("<rss><channel><item><title>Gold news</title><link>https://example.gov/a</link><pubDate>Tue, 06 Oct 2026 20:00:00 GMT</pubDate></item></channel></rss>","Test",1);}catch(Exception e){blocked=true;}check(blocked,"government article rejected by parser");
  System.out.println("PASS: "+count+" live-price/policy checks");
 }
}
