import java.net.*;import java.io.*;import java.security.*;import java.security.cert.*;import javax.net.*;import javax.net.ssl.*;import java.nio.charset.StandardCharsets;import org.java_websocket.client.WebSocketClient;
/** Test-only support for environments that provide an HTTP CONNECT proxy and CA bundle.
 * The Android application never uses this adapter. TLS validation stays enabled. */
public final class RuntimeProxy {
 static URI proxy;
 public static void configure()throws Exception{String value=System.getenv("HTTPS_PROXY");if(value==null||value.isEmpty())return;proxy=new URI(value);System.setProperty("https.proxyHost",proxy.getHost());System.setProperty("https.proxyPort",""+(proxy.getPort()>0?proxy.getPort():80));String ca=System.getenv("SSL_CERT_FILE");if(ca!=null&&!ca.isEmpty()){KeyStore keys=KeyStore.getInstance(KeyStore.getDefaultType());keys.load(null);CertificateFactory factory=CertificateFactory.getInstance("X.509");try(InputStream in=new FileInputStream(ca)){int i=0;for(java.security.cert.Certificate cert:factory.generateCertificates(in))keys.setCertificateEntry("ca-"+i++,cert);}TrustManagerFactory tm=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());tm.init(keys);SSLContext ctx=SSLContext.getInstance("TLS");ctx.init(null,tm.getTrustManagers(),null);SSLContext.setDefault(ctx);HttpsURLConnection.setDefaultSSLSocketFactory(ctx.getSocketFactory());}}
 public static void webSocket(WebSocketClient client){if(proxy==null)return;client.setDnsResolver(null);client.setSocketFactory(new SocketFactory(){public Socket createSocket(){return new Tunnel();}public Socket createSocket(String h,int p)throws IOException{Socket s=createSocket();s.connect(new InetSocketAddress(h,p));return s;}public Socket createSocket(String h,int p,InetAddress local,int lp)throws IOException{return createSocket(h,p);}public Socket createSocket(InetAddress h,int p)throws IOException{return createSocket(h.getHostAddress(),p);}public Socket createSocket(InetAddress h,int p,InetAddress local,int lp)throws IOException{return createSocket(h,p);}});}
 static class Tunnel extends Socket {public void connect(SocketAddress address,int timeout)throws IOException{InetSocketAddress destination=(InetSocketAddress)address;super.connect(new InetSocketAddress(proxy.getHost(),proxy.getPort()>0?proxy.getPort():80),timeout);setSoTimeout(15000);String target=destination.getHostString()+":"+destination.getPort();String auth="";if(proxy.getUserInfo()!=null)auth="Proxy-Authorization: Basic "+java.util.Base64.getEncoder().encodeToString(proxy.getUserInfo().getBytes(StandardCharsets.UTF_8))+"\r\n";getOutputStream().write(("CONNECT "+target+" HTTP/1.1\r\nHost: "+target+"\r\n"+auth+"\r\n").getBytes(StandardCharsets.US_ASCII));StringBuilder header=new StringBuilder();InputStream in=getInputStream();while(header.length()<16384&&!header.toString().endsWith("\r\n\r\n")){int c=in.read();if(c<0)throw new IOException("Proxy closed tunnel");header.append((char)c);}if(!header.toString().startsWith("HTTP/1.1 200")&&!header.toString().startsWith("HTTP/1.0 200"))throw new IOException("Proxy refused CONNECT tunnel");setSoTimeout(0);}}
}
